[platformio]
default_envs = native

[env:native]
platform = native @ 1.2.1
test_framework = unity
test_filter = native/*
lib_deps =
    bblanchon/ArduinoJson @ 7.4.3
build_flags = -std=c++17 -O2 -Wall -Wextra -DARDUINOJSON_USE_LONG_LONG=1
build_src_flags = -Wduplicated-branches -Wshadow -Wformat=2 -Werror
check_tool = cppcheck
check_src_filters = +<lib/> +<test/> -<.pio/>
check_skip_packages = yes
check_severity = high, medium
check_flags =
    cppcheck: --enable=warning,style,performance,portability --inline-suppr --std=c++17 --suppress=missingIncludeSystem --suppress=unusedFunction --suppress=preprocessorErrorDirective

[env:native_asan]
extends = env:native
build_flags = ${env:native.build_flags} -g -fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer
build_type = debug

[env:native_coverage]
extends = env:native
build_flags = -std=c++17 -O0 -g -Wall -Wextra -DARDUINOJSON_USE_LONG_LONG=1 --coverage -fprofile-abs-path
build_type = debug
extra_scripts = post:tools/gcov_link.py
